apiVersion: apps/v1
kind: Deployment
metadata:
  name: auto-enroll-deployment
  labels:
    app: auto-enroll
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auto-enroll
  template:
    metadata:
      labels:
        app: auto-enroll
    spec:
      imagePullSecrets:
      - name: "sf-gitlab-registry-creds"
      containers:
      - name: auto-enroll
        image: registry.gitlab.com/innovatrics/smartface/integrations-auto-enroll:0.2.1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
          - name: Config__Conditions__WatchlistIds__0
            value: "unknown"
          - name: Config__RegisterMinFaceSize
            value: "15"
          - name: Config__RegisterMaxFaceSize
            value: "600"
          - name: Config__RegisterFaceConfidence
            value: "400"
          - name: Config__DebugOutputFolder
            value: ""

          - name: Source__GraphQL__Host
            value: {{ .Values.smartface.graphqlApi.dnsHost }}
          - name: Source__GraphQL__Port
            value: "80"
          - name: Target__Host
            value: {{ .Values.smartface.authApi.dnsHost }}
          - name: Target__Port
            value: "443"
          - name: Target__Schema
            value: "https"

          - name: Source__OAuth__Url
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.configurations.auth.existingSecretName }}
                key: {{ .Values.configurations.auth.oauthTokenUrlKey }}
          - name: Source__OAuth__Audience
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.configurations.auth.existingSecretName }}
                key: {{ .Values.configurations.auth.audienceKey }}
          
          - name: Source__OAuth__ClientId
            valueFrom:
              secretKeyRef:
                name: {{ .Values.configurations.tenantAuth.existingSecretName }}
                key: {{ .Values.configurations.tenantAuth.clientIdKey }}
          - name: Source__OAuth__ClientSecret
            valueFrom:
              secretKeyRef:
                name: {{ .Values.configurations.tenantAuth.existingSecretName }}
                key: {{ .Values.configurations.tenantAuth.clientSecretKey }}
          

