apiVersion: v1
kind: Secret
metadata:
  name: firebase-secrets
type: Opaque
stringData:
  FE_VAPID_KEY:                         {{ .Values.configurations.firebase.vapidPublicKey | quote }}
  NODE_TYPE:                            {{ .Values.configurations.firebase.nodeType | quote }}
  NODE_PROJECT_ID:                      {{ .Values.configurations.firebase.projectId | quote }}
  NODE_PRIVATE_KEY_ID:                  {{ .Values.configurations.firebase.privateKeyId | quote }}
  NODE_PRIVATE_KEY:                     {{ .Values.configurations.firebase.privateKey | quote }}
  NODE_CLIENT_EMAIL:                    {{ .Values.configurations.firebase.clientEmail | quote }}
  NODE_CLIENT_ID:                       {{ .Values.configurations.firebase.clientId | quote }}
  NODE_AUTH_URI:                        {{ .Values.configurations.firebase.authUri | quote }}
  NODE_TOKEN_URI:                       {{ .Values.configurations.firebase.tokenUri | quote }}
  NODE_AUTH_PROVIDER_X509_CERT_URL:     {{ .Values.configurations.firebase.authProviderx509CertUrl | quote }}
  NODE_CLIENT_X509_CERT_URL:            {{ .Values.configurations.firebase.clientx509CertUrl | quote }}
  NODE_UNIVERSE_DOMAIN:                 {{ .Values.configurations.firebase.universeDomain | quote }}
  